# fly.toml app configuration file generated for thebackend on 2025-02-27T00:29:25+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'thebackend'
primary_region = 'bom'
kill_signal = 'SIGTERM'

[build]

[env]
  MIX_ENV = 'prod'
  PHX_HOST = 'thebackend.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
